### ISSUE TITLE
ADPCM decreased volume

### ISSUE THREAD

**Issue by SY-24** [XAYRGA/jatast#5]
Hey again,

thanks for all your efforts towards this encoder. I found just one more issue that I'd like to point out and hope it can be fixed eventually.

Sometimes I double-check my encoded ast files in MPC-HC or Audacity before putting them into my game. Thus I noticed about adpcm4 encodes that they tend to be quieter than pcm16 encoded files.

_Maybe this is just the nature of afc_adpcm, and if so please feel free to ignore this post._

I made a comparison. You should get similar/identical results when testing this privately. And to make sure it's not a mistake of Audacity's decoder, I put recordings from the emulator alongside.

![ADPCM-PCM16-Compare](https://user-images.githubusercontent.com/92381752/188216080-e46b6ba3-3042-44f5-a1ee-9c591edd75d2.png)

Again, I highly appreciate all your efforts and it would be awesome once the last few tweaks are worked out.

**Comment by XAYRGA** [comment]
This is both the nature of ADPCM4 and a quirk with the encoder, which is being reworked (slowly). 

ADPCM4 can sometimes experience some forms of fidelity or volume loss, but particularly the problem you're talking about is likely the fact that the prescale on the encoder has to scale the samples by 75%, otherwise there's a strange issue with encoding that results in an overflow of the floating sample value, and thusly results in screaming from the stream.

[You can see what i'm talking about here, or below](https://github.com/XAYRGA/jatast/blob/main/jatast/bananapeel/banan_flaaf.cs#L75)

![encoder](https://xayr.ga/share/09-2022/devenv_f2a1fbfe-4bc7-4958-bcf5-db3beaf67c39.png)

There is a commandline parameter that you can use to adjust the gain on the encoder at this time, but use it at your own risk: 

**-bananapeel.gain (float value)**

**Comment by SY-24** [comment]
I tried the extra parameter, though I couldn't quite get it working. Attempted with
```
-bananapeel.gain 1.25
-bananapeel.gain = 1.25
```
but ended up with the same audio-waves as shown in my image above. The encoder prints a message regarding this:
```
JATAST -- JAudio Toolkit AST creator
Number argument for '-bananapeel.gain' expected.
Encoding in ADPCM4 -- Report any bugs to the github page!
```

I remember SMG2 having an extra file that lets you control the volume of music streams, called BgmParam.bcsv. Don't know if the other JAudio based games have that, but this would be my workaround for now.

**Comment by XAYRGA** [comment]
> I tried the extra parameter, though I couldn't quite get it working. Attempted with
> 
> ```
> -bananapeel.gain 1.25
> -bananapeel.gain = 1.25
> ```
> 
> but ended up with the same audio-waves as shown in my image above. The encoder prints a message regarding this:
> 
> ```
> JATAST -- JAudio Toolkit AST creator
> Number argument for '-bananapeel.gain' expected.
> Encoding in ADPCM4 -- Report any bugs to the github page!
> ```
> 
> I remember SMG2 having an extra file that lets you control the volume of music streams, called BgmParam.bcsv. Don't know if the other JAudio based games have that, but this would be my workaround for now.

For this, it seems I had the argument parsing wrong, give it another try if you're up for it, latest commit should fix the argument. As for the encoder's default volume it'll have to be put to the side for now, until I can resolve the looping issue (#4 ) / remake the encoder, as both of those will determine how this issue is handled. 

In JSystem games, there is a section of the BAA called the SoundTable which has parameter controls for each of the sound files, this includes SMG1+2. The tool for adjusting this is https://github.com/xayrga/bast here.

Or you can get premade scripts for tampering with it http://www.xayr.ga/tools/SoundModdingToolkit/ here.

**Comment by XAYRGA** [comment]
Fixed in "Castle Bravo" release.

**Comment by Github3010** [comment]
Please re-clone https://github.com/ZyphronG/Zucchini! It has been down for days!
